name:                POWERMath
version:             0.1.0.0
github:              "githubuser/POWERMath"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/POWERMath#readme>

default-extensions:
- DataKinds
- TypeApplications
- TypeFamilies
- MultiParamTypeClasses

dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- containers
- array
- pretty
- pretty-simple
- fgl
- process
- syb
- directory
- unix
- QuickCheck
- bytestring
- text
- parallel
- random
- old-time
- time
- vector
- parsec
- split
- filepath
- transformers
- template-haskell
- utf8-string
- hashable
- deepseq
- HashedExpression
- CoconutPrelude
- hspec
- HUnit
- bytestring-trie
- unordered-containers
- primitive

ghc-options:
# - -Wall
- -Wcompat
# - -Widentities
# - -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
# - -Wmissing-export-lists
# - -Wmissing-home-modules
# - -Wpartial-fields
# - -Wredundant-constraints

library:
  source-dirs:
    - src
    - CoconutBase/src

executables:
  POWERMath-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - POWERMath

tests:
  POWERMath-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -main-is Spec
    dependencies:
    - POWERMath
